# Generated by Django 3.0.3 on 2020-04-04 15:21

import backend.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=backend.gallery.models.get_path_upload_image, verbose_name='Фото'),
        ),
    ]
