# Generated by Django 3.0.3 on 2020-04-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200404_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Фото'),
        ),
    ]
