# Generated by Django 3.0.3 on 2020-04-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='filter',
            new_name='filters',
        ),
    ]
