# Generated by Django 3.0.3 on 2020-04-06 22:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0002_auto_20200402_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notice_board.Category', verbose_name='Родитель'),
        ),
    ]
